try {
  brokenFunction();
} catch (e) {
  console.error(e.message);
}
